### ISSUE TITLE
importerror for module `commands`

### ISSUE THREAD

**Issue by manodeep** [chenwuperth/rgz_rcnn#3]
While trying to run `python download_data.py`, I get an import error:

```
Traceback (most recent call last):
  File "download_data.py", line 27, in <module>
    import commands
ModuleNotFoundError: No module named 'commands'
```
```
$ python --version
Python 3.6.3 :: Anaconda custom (64-bit)
```
Is the model `python2` only?

**Comment by chenwuperth** [comment]
Thank you @manodeep for raising this issue. Yes, as suggested in the README, it currently supports Python 2.7 only, but I will make it Python3 compatible in the next few days. Please stay tuned, and I will let you know when that is ready.

**Comment by manodeep** [comment]
I used the `python-modernize` to update my fork. Please feel free to open a PR to see if the changes are acceptable.

Thanks!

**Comment by chenwuperth** [comment]
Since [ClaRAN v0.2](https://github.com/chenwuperth/claran) is out now, and it is based on Python 3 exclusively. So I will close this ticket now. Thanks!
