### ISSUE TITLE
Needed to Download Grade to TensorFlow 1.5

### ISSUE THREAD

**Issue by FernOfGitHub** [chenwuperth/rgz_rcnn#5]
FYI.

Received Illegal Instruction (core dump) on 'import tensorflow' in demo.py
Had run 'pip install tensorflow'. The latest version is 1.6
Uninstalled and ran 'pip install tensorflow==1.5'

No more problems.
Tensorflow website states Tensorflow 1.6 uses AVX. I have an i7 (older model). Don't understand the problem with 1.6, but 1.5 is working.

**Comment by chenwuperth** [comment]
Thank you for the notice. Our experience with TF1.1, 1.4 and 1.8 appears fine with ClaRAN. We never tried 1.6, however I suspect this is more of a system/python issue. Hence, I will close this ticket. Hope 1.5 works fine for you!
