### ISSUE TITLE
Replicating the infrared PNG images

### ISSUE THREAD

**Issue by cvbuchem** [chenwuperth/rgz_rcnn#7]
Currently I am seeing if CLARAN can be used on data gathered in the LOFAR survey. In order to do this I would like to replicate the .png images that were generated using the WISE data. The only problem is that I can not seem to find any documentation of the scaling/colormap that was used when generating these images. 

Any suggestions as to where I could look in order to find this information? 

Searching through the Radio Galaxy Zoo github repository did not deliver any results.

**Comment by chenwuperth** [comment]
Could you try starting from this lineline:https://github.com/chenwuperth/rgz_rcnn/blob/master/tools/fits_utils.py#L320

(the comment needs to be updated, but it is how we generate WISE PNG from WISE fits file with color map details).

Does that help with solving your issue? Please feel free to post any issues on data pre-processing for testing ClaRAN on LOFAR survey.

**Comment by cvbuchem** [comment]
Thanks for the suggestion!
```
cmd_tpl = '%s -cmap gist_heat -cmap value 0.684039 0'\
' -zoom to fit -scale log -scale mode minmax -export %s -exit'
```
Appears to contain all the export specifications for DS9 which should be enough to replicate the scaling/normalization in aplpy or matplotlib.

**Comment by chenwuperth** [comment]
Good. the "cmd_tpl solution" is essentially a hack. I will be very interested to learn more about your matplotlib solution when it is available.... thanks.
