### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by ritwik12** [chenwuperth/rgz_rcnn#9]
We need to specify the exact TensorFlow version in our code as using `pip install tensorflow` installs the latest version of TensorFlow which is `2.0` but with that our code gives error for 

```
 self.data = tf.placeholder(tf.float32, shape=[None, None, None, 3])
AttributeError: 'module' object has no attribute 'placeholder'
```

as placeholder is deprecated, code works well for `tensorflow==1.14`

**Comment by chenwuperth** [comment]
Yes, thank you for pointing that out! I have added version restrictions on the READ.ME now.

**Comment by ritwik12** [comment]
@ritwik12 Your welcome
